#https://registry.hub.docker.com/r/codercom/code-server/
version: '3'
services:
  vscode:
    build: ./vscode
    ports:
      - "8080:8080"
    volumes:
      - ./vscode:/vscode
      - ./vscode/.config/config.yaml:/home/coder/.config/code-server/config.yaml
    links:
     - minecraft-server
  minecraft-server:
    image: "itzg/minecraft-server"
    container_name: "mc-pi-srv"
    ports:
      - "25565:25565"
      - "4711:4711"
    expose:
      - "25565"
    volumes:
      - "./spigot/data:/data"
      - "./spigot/server.properties:/data/server.properties"
      - "./spigot/plugins:/plugins"
    environment:
      EULA: "TRUE"
      TYPE: "SPIGOT"
      VERSION: "1.11.2"
      MEMORY: "5G"
    tty: true
    stdin_open: true
